// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('WEB_API_KEY', defaultValue: ''),
    appId: String.fromEnvironment('WEB_APP_ID', defaultValue: ''),
    messagingSenderId: String.fromEnvironment(
      'MESSAGING_SENDER_ID',
      defaultValue: '',
    ),
    projectId: String.fromEnvironment('PROJECT_ID', defaultValue: ''),
    authDomain:
        '${String.fromEnvironment('PROJECT_ID', defaultValue: '')}.firebaseapp.com',
    storageBucket:
        '${String.fromEnvironment('PROJECT_ID', defaultValue: '')}.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('ANDROID_API_KEY', defaultValue: ''),
    appId: String.fromEnvironment('ANDROID_APP_ID', defaultValue: ''),
    messagingSenderId: String.fromEnvironment(
      'MESSAGING_SENDER_ID',
      defaultValue: '',
    ),
    projectId: String.fromEnvironment('PROJECT_ID', defaultValue: ''),
    storageBucket:
        '${String.fromEnvironment('PROJECT_ID', defaultValue: '')}.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('IOS_API_KEY', defaultValue: ''),
    appId: String.fromEnvironment('IOS_APP_ID', defaultValue: ''),
    messagingSenderId: String.fromEnvironment(
      'MESSAGING_SENDER_ID',
      defaultValue: '',
    ),
    projectId: String.fromEnvironment('PROJECT_ID', defaultValue: ''),
    storageBucket:
        '${String.fromEnvironment('PROJECT_ID', defaultValue: '')}.firebasestorage.app',
    iosBundleId: String.fromEnvironment('IOS_BUNDLE_ID', defaultValue: ''),
  );
}
