// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT7zQbj0tMdmP1gbDenjbvULqbDQWtO60',
    appId: '1:557379891934:web:3a42295acc8d853f39884f',
    messagingSenderId: '557379891934',
    projectId: 'bikespot-nyc',
    authDomain: 'bikespot-nyc.firebaseapp.com',
    storageBucket: 'bikespot-nyc.firebasestorage.app',
    measurementId: 'G-CN9MBT0CQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9NAnyYzFbMv06xyfrLzNryODoBOaZY9g',
    appId: '1:557379891934:android:5e22b8aa0a77fc9f39884f',
    messagingSenderId: '557379891934',
    projectId: 'bikespot-nyc',
    storageBucket: 'bikespot-nyc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbcSQ9PEAnTI9n16hEelPd0ZuJQhidBrw',
    appId: '1:557379891934:ios:19c9ade07b92233639884f',
    messagingSenderId: '557379891934',
    projectId: 'bikespot-nyc',
    storageBucket: 'bikespot-nyc.firebasestorage.app',
    iosBundleId: 'com.visokolov.bikespotnyc',
  );
}
