name: Flutter Android CI

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
      - flutter_map
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  build_android:
    runs-on: ubuntu-latest # Use an Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17' # Specify Java version required by Android

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4' # Specify your Flutter version

      - name: Get packages
        run: flutter pub get

      - name: Build Android APK
        run: flutter build appbundle

      - name: Build and Sign Release AAB
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          alias: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          keyPassword: ${{ secrets.ANDROID_KEYALIAS_PASS }}

      - name: Upload Signed App Bundle as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}

  deploy:
    name: Deploy to Play Store
    needs: build_android
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-bundle
          path: app/build/outputs/bundle/release

      - name: Publish to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.visokolov.bikespotnyc # Replace with your app's package name
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: internal # Use 'production', 'beta', or 'alpha' for other tracks
          status: draft
